# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            keeping.client:
                base_uri: '%env(KEEPING_API_BASE_URL)%'
                auth_bearer: '%env(KEEPING_API_PA_TOKEN)%'
                headers: 
                    Content-Type: 'application/json'
                    Accept: 'application/json'
                    Connection: 'keep-alive'
                verify_peer: false
                verify_host: false
            clockify.client:
                base_uri: '%env(CLOCKIFY_API_BASE_URL)%'
                auth_bearer: '%env(CLOCKIFY_API_TOKEN)%'
                headers: 
                    Content-Type: 'application/json'
                    Accept: 'application/json'
                    Connection: 'keep-alive'
                verify_peer: false
                verify_host: false
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
